### PR TITLE
Integrates Airtable database with app

### LINKED ISSUE #13: Week 7 - Airtable Integration
### Expected App Capabilities

After completing this week's assignment, your app should:

- Save todos to an Airtable base
- Load saved todos from Airtable on loading
- Display pending messages during network requests
- Display error messages on network or authentication error

### Instructions Part 1: Set up Airtable Base

An Airtable base is a collection of tables that stores data, similar to a database, but with a user-friendly interface that resembles a spreadsheet. Each base can contain multiple tables, each with its own set of rows and columns to organize and store different types of information.

We will use an Airtable table as an API to save data for the todo list.

#### Before You Begin

You'll need a place to store your personal access token, base id, and table name. These are details that we do not want to publish with our project so we'll use an environment file, .env.local. It has already been listed in the project's .gitignore so we don't have to worry about it being saved into version control.

After creating this week's working branch, create a environment file, `.env.local`, in the base directory of the project then paste in the following text:

```text
VITE_PAT=super_secret
VITE_BASE_ID=xxxxxxxxxxxxxxxxx
VITE_TABLE_NAME=TableName
```

As you go through the setup and documentation, you'll save those values for the project's use.

#### Create Base

- Your first steps is to [sign up for an Airtable account](https://airtable.com/signup). Once completed, follow the screenshots to set up your todo's base.
- Choose the Create button at the bottom left and choose to start from scratch.

choose start from scratch

- Rename the table's default name of "Table 1" to "Todos" by clicking on the down arrow on Table 1's tab.
- Save the table name to your environment file under the variable `VITE_TABLE_NAME`
- Update the first field name so that it reads "title" instead of "Title".
- Delete the other fields.

hit down arrow and select edit field

- Create a new checkbox field named "isCompleted". This type of field acts a boolean.

add isCompleted field

#### Generate Connection Credentials

- Click on profile picture to open menu.
- Select "Builder hub"

navigate to builder hub

- Select "Create new token".

create a new personal access token

- Give the token a name that you'll remember.
- Add the scopes `data.records:read` and `data.records.write`
- Under the Access heading. Hit "Add a base" and choose your new one.
- Hit "Save changes" Copy the token value that shows on the next screen
- Save it to `VITE_PAT` in your environment file.

configure access token

- We next have to find the base's id - one approach is to use the API documentation accessed from the base's help menu.

navigate to customized api documentation

- After the introduction paragraphs, the documentation includes your personal base's id. Save that to `VITE_BASE_ID` in the environmental file.

documentation is customized to match base config

Take some time to look over the documentation for Airtable. As you read it over, keep in mind that we will **not** be using Airtable's JavaScript API client. It does not provide anything useful for us in React so it's better to look at the `curl` examples. That'll let you see how the urls and payloads look. Some of the things you can do with the API are pretty cool! Go take a look!

> [!note]
> The backslash `\` in the `curl` code examples lets us hit enter to continue adding arguments to the `curl` command.

```terminal

## using backslash

curl "https://api.airtable.com/v0/app8c6VR6IQ26pgKP/Todos?maxRecords=3&view=Grid%20view" \
  -H "Authorization: Bearer super_secret_api_key"

## without backslash and new line, it's harder to read the command

curl "https://api.airtable.com/v0/app8c6VR6IQ26pgKP/Todos?maxRecords=3&view=Grid%20view" -H "Authorization: Bearer super_secret_api_key"
```

### Instructions Part 2 : Load Todos from Airtable

You will be updating your app to load the todos from Airtable and adopting a pessimistic update approach. While the todos are loading, you'll display a wait message to the user.

In App.jsx:

#### Establish Transition State

- Create an `isLoading` state variable with with a `defaultValue` of `false`. Destructure out its associated update function, `setIsLoading`, too.
- Create another state variable but name it `errorMessage` and default to an empty string, `""`. Include its update function too.

#### Fetch in App

You will use the `useEffect` hook to define and send off the initial fetch request that loads the todos from Airtable. You'll also work with `isLoading` to conditionally show a loading message to the user. If we ever have to make a user wait, it's important to indicate that our app is in the middle of a slow process. This lets the user know that the app is processing a request and they should wait for it to complete.

While still in App.jsx:

- Create constants, `url` and `token`, which will be used in the fetch requests.
  - ``const url = `https://api.airtable.com/v0/${import.meta.env.VITE_BASE_ID}/${import.meta.env.VITE_TABLE_NAME}`;``
  - ``const token = `Bearer ${import.meta.env.VITE_PAT}`;``
- create the `useEffect` that was discussed above:
  - Give it an empty dependency array.
  - In the body of the function in `useEffect`'s first argument do the following:
    - Define an async anonymous arrow function that takes no arguments and save it to `fetchTodos`
    - Make sure to call `fetchTodos()` before closing out the `useEffect`'s first argument.

So far, it should look like:

```jsx
{/*extract from App.jsx*/}
{/*...code*/}
useEffect(() => {
    const fetchTodos = async () => {};
    fetchTodos();
}, [])
{/*code continues...*/}
```

- continuing in `fetchTodos`
  - Use `setIsLoading` to update `isLoading` to `true`
  - Create an `options` object for the fetch request. Include:
    - A `method` property set to "GET",
    - And a `headers` property set to an object containing the following key/value pair: `"Authorization": token`.
  - Set up `try/catch/finally` blocks to handle the fetch:
    - in `try`
      - Save an awaited `fetch` to the const `resp` and pass in the `url` and `options` : `const resp = await fetch(url, options);`
      - If `resp.ok` evaluates to false in an `if` statement, throw a new `Error` that takes in `resp.message`.

After the `if` block that throws, you'll place your remaining logic to process the API's response.

- Await the value that `response.json()` returns. We will be working with the `records` array in the response. An example response would be:

```JSON
{
    "records": [
        {
            "id": "recEAx4TQF6JjzZLV",
            "createdTime": "2025-02-19T22:04:12.000Z",
            "fields": {
                "title": "test todo"
            }
        },
        {
            "id": "recx22h6JwjsMhCku",
            "createdTime": "2025-02-19T22:04:15.000Z",
            "fields": {
                "isCompleted": true,
                "title": "make dinner"
            }
        },
        {
            "id": "recFwX5Nyp1TpkUXI",
            "createdTime": "2025-02-19T22:04:17.000Z",
            "fields": {
                "title": "code out assignment examples"
            }
        }
    ]
}
```

There are several important details to note when you compare this response against the `todoList` state value:

- The properties, `isCompleted` and `title` are stored in a `fields` object.
- The `id` is at the top level of each todo object.
- Any fields that equal false or contain an empty string will not be returned with the todos.
- The `records` value will always be an array.

Because the "shape" of each todo is different than how they are represented in the app's `todoList` array, you will have to map the contents of `record` out of the response body. The same will be true for the payload of any PUT and PATCH requests.

- in a `map` method called on `records`, define an anonymous function:
  - It takes a `record` param.
  - It contains a `const todo = {}`.
  - Inside the object, assign the `record` properties to the appropriate todo properties.
  - If `isCompleted` is not truthy, you will want to explicitly set the property equal to `false`.

Use the below `map` examples as reference if needed:

```js
//example map from an Airtable response.records

const response = await response.json();
const fetchedExamples = response.records.map((record) => {
    const example = {
        id: record.id,
        //destructuring is a compact way to move all fields over
        //won't need to change this a lot as the app evolves
        ...record.fields,
        };
    if(!example.booleanProperty){
        //Airtable doesn't return properties whose values are false or empty strings
        //explicity setting property to false so field exists and prevents logic bugs
        example.booleanProperty = false;
    }
    return example;
})
setExamples([...fetchedExamples])
```

-or a more compact version-

```js
const {records} = await response.json()
setExamples(records.map(record)=> {
    const example = {
    id: record.id,
    ...record.fields,
    };
    if(!example.booleanProperty){
        example.booleanProperty = false;
    }
    return example;
})

```

After this, it's time to move on to the `catch` and `finally` blocks.

- The `catch` block:
  - Takes in an error parameter.
  - Use `setErrorMessage` with `error.message` to set an error message that we will display to the user shortly.
- The `finally` bock:
  - Set the `isLoading` state value back to false.

#### Display Loading Indicator in TodoList

- While still in App.jsx, pass `isLoading` into props for the `TodoList` instance.
- In TodoList:
  - Destructure `isLoading` out of its props.
  - Add a statement that evaluates `isLoading` in the JSX that conditionally renders the existing paragraph OR a new paragraph for the loading message.
  - The new paragraph should have a loading message to display the user. Eg: `<p>Todo list loading...</p>`

At this point, the todo list should display a message while the API is loading the todos. Once the fetch resolves, it re-renders with the todo list (Or the original paragraph if 0 todos are loaded).

todo list displays loading message

#### Display Error

In App:

- Add conditional block after the `TodoList` instance. Use the block to evaluate `errorMessage`.
  - If not empty, display a div containing:
    - A horizontal rule `<hr/>`.
    - A paragraph that renders `errorMessage`.
    - A dismiss button that empties `errorMessage`.

When an error happens with our initial fetch, a message is displayed to the user. We've intentionally made this setup as simple as possible so that we can re-use this error message for other operation errors.

### Instructions Part 3: Update Add New Todo Functionality

In part 3, you'll use an pessimistic state update approach for adding todos. You'll use transient state to change the text content of the button while the request is processing. We don't want pause the user but it's useful for them to know that the application is processing the last action before their todo is rendered . When the API has processed the response, the todo in the payload response gets added into the todo list state.

In App:

- Create state value`isSaving` with a `defaultValue` of false. You will need its update function too.
- In the add todo button
  - Replace the button text with a ternary block that evaluates `isSaving`.
    - If true, display "Saving..."
    - If `false`, display "Add Todo" or the text value you were already using.

It should now look like:

```jsx
<button disabled={workingTodoTitle.trim() === ''}>
    {isSaving ? 'Saving...' : 'Add Todo'}
</button>
```

- Update `addTodo(newTodo)`:
  - Convert it to an async function.
  - Inside the function body...
    - Create a `payload` object containing a `records` array containing a single todo object.
    - Create an `options` object for the fetch request:
      - Use the "POST" method.
      - Use the same header options from the last request.
      - Stringify the `payload` object for `options.body`.

At this point, `addTodo` should look like:

```jsx
{/*extract from App.jsx*/}
{/*...code*/}

const addTodo = async (newTodo) => {
    const payload = {
      records: [
        {
          fields: {
            title: newTodo.title,
            isCompleted: newTodo.isCompleted,
          },
        },
      ],
    };
    const options = {
      method: 'POST',
      headers: {
        Authorization: token,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    };
{/*code continues...*/}
```

- Continuing from inside `addTodo`
  - `try` block logic:
    - Set `isSaving` true.
    - Send a fetch request and assign it's awaited return value to `resp`.
      - (hint: `const resp = await fetch(url, options);`)
      - Throw an Error if `!resp.ok`
    - Destructure the `records` from the response by using `const { records } = await resp.json();`
    - Create a `savedTodo` object that:
      - assigns the `id` to the first array entry's id property.
      - destructures the remaining key/values pairs out of the only `records` object.
    - If the `isCompleted` property in the `records` object is not true, explicitly set that on property on `savedTodo` to `false`
      - This looks like `if (!records[0].fields.isCompleted) {savedTodo.isCompleted = false;}`
      - Recall that Airtable does not return false or empty fields in the `records`.
    - Update state using `setTodoList([...todoList, savedTodo]);`
  - `catch` block logic:
    - Log the error to console.
    - Update `setErrorMessage` state value with `error.message`. This will cause errors to show up for users.
  - `finally` block:
    - Set `isSaving` to false.

The updates you've made should flash a brief message on the button while the response processes:

saving message shows briefly on submit button

### Instructions Part 4: Update Functionality of Update and Complete Todo

For the final two refactors, you will be using an optimistic approach to UI management. This introduces the need to undo state changes and communicate unexpected API failures to the user. You'll set the updated value into state at the beginning of the `updateTodo` function but not before saving the original version temporarily. If there's a network disruption or some other issue that causes the fetch to fail, you'll use this original version to revert the todoList state back to its state before the error.

#### Update Todos Functionality

In App:

- update `updateTodo:
  - Convert it to an async function.
  - Save the original todo to `originalTodo`:
    - By finding it's associated object in the `todoList` array by each object's id.
    - It should look like: `const originalTodo = todoList.find((todo) => todo.id === editedTodo.id)`
  - Create `payload` object for the fetch request using `editedTodo`
    - The API expects `payload` to be a JSON object containing a `records` array of table records for the Todo table. For reference, here's the JavaScript object you define in preparation to do this:

```JSON
const payload = {
    records: [
        {
            id: editedTodo.id,
            fields: {
                title: editedTodo.title,
                isCompleted: editedTodo.isCompleted,
            },
        },
    ],
};
```

- Continued...
  - Create an `options` object for the fetch request.
    - Use the PATCH method.
    - Use the same Authentication header and include `'Content-Type': 'application/json'` in the `headers` object.
    - For the `body` property, convert the `payload` object to a JSON string using `JSON.stringify(payload)`
  - `try` block:
    - Send a fetch request using `url` as the endpoint and the `options` object just created.
      - Throw an error if `!resp.ok`.
  - `catch` block:
    - Log the error to console.
    - Update `errorMessage` using the ``setErrorMessage(`${error.message}. Reverting todo...`);``
    - Create a `revertedTodos` using the `originalTodo` to reset that todo's value to a previous state.
    - Update state with `setTodoList([...revertedTodos]);`
  - `finally` block:
    - Set the state value, `isSaving`, to false.

In TodoListItem:

We need to cover an edge case where an outdated value is displayed when a user saves a todo and clicks it again immediately.

- add a useEffect that resets the `workingTitle` to the `todo` prop's `.title` value
  - add `todo` to the dependency array.
  - call `setWorkingTitle` and pass in the value of `todo.title`

At this point, the todo app should:

1. Load the todos from Airtable.
2. Create new todos with the todo form and persist them in Airtable.
3. Allow users to edit todos which will then update in Airtable.
4. Display errors messages to the user if there are any fetch issues.

error displayed to user at bottom of screen

#### Update Functionality to Complete Todos

You'll be left to update `completeTodo` with the necessary logic to communicate the completed todo to the Airtable API and keep the UI synced. You can use `updateTodo` as a reference as you work through this final portion. So that you have a checklist of details to think about: the final code should:

- [ ] optimistically update the UI:
  - [ ] The todo completes immediately in the UI immediately and allows user to continue to work with the todo list.
  - [ ] The fetch request happens in the background unless there's a request error.
  - [ ] The UI for the todo list reverts to its original state if the fetch response does not come back okay.
  - [ ] Display an error message to the user, using the `errorMessage` state if fetch encounters any problems.
- [ ] Fetch should use the same headers and method, and take in a payload very similar to the fetch found in `updateTodo`
- [ ] The same object transformation has to happen between the todo object as represented in state and the todo represented in the `records` property on the payload.

### Stretch Goals: Refactor for Reusable Code

You will probably have noticed that you are starting to introduce some duplicate code. While that is okay during prototyping and early development, before submitting any final code for a feature (in our case, this assignment), take the time to refactor your code to make it **[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)**. This will keep the codebase clean and easy to manage. Remember that you should commit your code now so that you have a good save point to return to if you need to start the refactor over again.

- Look for any items that are defined multiple times and assign them to a variable.
- Compare functions or procedures to find common logic that could be shared in a helper or utility function.
- Brainstorm some more user-friendly error messages.
- If you visual learner and have to add styling to help visualize the interface better:
  - Stick to class-based styles that you define in App.css.
  - Don't restructure anything in the JSX. We want to maintain a semantically sound html structure so that when we cover styling in week 10, several style choices applied during the assignment will work out properly.
  - Have fun but don't let styling get away of completing the weekly lesson. After all, a baker doesn't ice a cake until after it's baked and cooled.

### Closing Notes

 Next week we cover sorting and filtering. The discussion will take us through implementing sorting and searching on both local and API data stores. We'll then implement an API-based sorting and filtering strategy.

### PR DESCRIPTION
**Pull request by mnichols08**
Closes #13 

### Expected App Capabilities

After completing this week's assignment, your app should:

- [x] Save todos to an Airtable base
- [x] Load saved todos from Airtable on loading
- [x] Display pending messages during network requests
- [x] Display error messages on network or authentication error

### Instructions Part 1: Set up Airtable Base

An Airtable base is a collection of tables that stores data, similar to a database, but with a user-friendly interface that resembles a spreadsheet. Each base can contain multiple tables, each with its own set of rows and columns to organize and store different types of information.

We will use an Airtable table as an API to save data for the todo list.

#### Before You Begin

You'll need a place to store your personal access token, base id, and table name. These are details that we do not want to publish with our project so we'll use an environment file, .env.local. It has already been listed in the project's .gitignore so we don't have to worry about it being saved into version control.

After creating this week's working branch, create a environment file, `.env.local`, in the base directory of the project then paste in the following text:

```text
VITE_PAT=super_secret
VITE_BASE_ID=xxxxxxxxxxxxxxxxx
VITE_TABLE_NAME=TableName
```

As you go through the setup and documentation, you'll save those values for the project's use.

#### Create Base

- [x] Your first steps is to [sign up for an Airtable account](https://airtable.com/signup). Once completed, follow the screenshots to set up your todo's base.
- Choose the Create button at the bottom left and choose to start from scratch.

choose start from scratch

- [x] Rename the table's default name of "Table 1" to "Todos" by clicking on the down arrow on Table 1's tab.
- [x] Save the table name to your environment file under the variable `VITE_TABLE_NAME`
- [x] Update the first field name so that it reads "title" instead of "Title".
- [x] Delete the other fields.

hit down arrow and select edit field

- [x] Create a new checkbox field named "isCompleted". This type of field acts a boolean.

add isCompleted field

#### Generate Connection Credentials

- [x] Click on profile picture to open menu.
- [x] Select "Builder hub"

navigate to builder hub

- [x] Select "Create new token".

create a new personal access token

- [x] Give the token a name that you'll remember.
- [x] Add the scopes `data.records:read` and `data.records.write`
- [x] Under the Access heading. Hit "Add a base" and choose your new one.
- [x] Hit "Save changes" Copy the token value that shows on the next screen
- [x] Save it to `VITE_PAT` in your environment file.

configure access token

- [x] We next have to find the base's id - one approach is to use the API documentation accessed from the base's help menu.

navigate to customized api documentation

- [x] After the introduction paragraphs, the documentation includes your personal base's id. Save that to `VITE_BASE_ID` in the environmental file.

documentation is customized to match base config

Take some time to look over the documentation for Airtable. As you read it over, keep in mind that we will **not** be using Airtable's JavaScript API client. It does not provide anything useful for us in React so it's better to look at the `curl` examples. That'll let you see how the urls and payloads look. Some of the things you can do with the API are pretty cool! Go take a look!

> [!note]
> The backslash `\` in the `curl` code examples lets us hit enter to continue adding arguments to the `curl` command.

```terminal

## using backslash

curl "https://api.airtable.com/v0/app8c6VR6IQ26pgKP/Todos?maxRecords=3&view=Grid%20view" \
  -H "Authorization: Bearer super_secret_api_key"

## without backslash and new line, it's harder to read the command

curl "https://api.airtable.com/v0/app8c6VR6IQ26pgKP/Todos?maxRecords=3&view=Grid%20view" -H "Authorization: Bearer super_secret_api_key"
```

### Instructions Part 2 : Load Todos from Airtable

You will be updating your app to load the todos from Airtable and adopting a pessimistic update approach. While the todos are loading, you'll display a wait message to the user.

In App.jsx:

#### Establish Transition State

- [x] Create an `isLoading` state variable with with a `defaultValue` of `false`. Destructure out its associated update function, `setIsLoading`, too.
- [x] Create another state variable but name it `errorMessage` and default to an empty string, `""`. Include its update function too.

#### Fetch in App

You will use the `useEffect` hook to define and send off the initial fetch request that loads the todos from Airtable. You'll also work with `isLoading` to conditionally show a loading message to the user. If we ever have to make a user wait, it's important to indicate that our app is in the middle of a slow process. This lets the user know that the app is processing a request and they should wait for it to complete.

While still in App.jsx:

- [x] Create constants, `url` and `token`, which will be used in the fetch requests.
  - [x] ``const url = `https://api.airtable.com/v0/${import.meta.env.VITE_BASE_ID}/${import.meta.env.VITE_TABLE_NAME}`;``
  - [x] ``const token = `Bearer ${import.meta.env.VITE_PAT}`;``
- [x] create the `useEffect` that was discussed above:
  - [x] Give it an empty dependency array.
  - [x] In the body of the function in `useEffect`'s first argument do the following:
    - [x] Define an async anonymous arrow function that takes no arguments and save it to `fetchTodos`
    - [x] Make sure to call `fetchTodos()` before closing out the `useEffect`'s first argument.

So far, it should look like:

```jsx
{/*extract from App.jsx*/}
{/*...code*/}
useEffect(() => {
    const fetchTodos = async () => {};
    fetchTodos();
}, [])
{/*code continues...*/}
```

- continuing in `fetchTodos`
  - [x] Use `setIsLoading` to update `isLoading` to `true`
  - [x] Create an `options` object for the fetch request. Include:
    - [x] A `method` property set to "GET",
    - [x] And a `headers` property set to an object containing the following key/value pair: `"Authorization": token`.
  - Set up `try/catch/finally` blocks to handle the fetch:
    - in `try`
      - [x] Save an awaited `fetch` to the const `resp` and pass in the `url` and `options` : `const resp = await fetch(url, options);`
      - [x] If `resp.ok` evaluates to false in an `if` statement, throw a new `Error` that takes in `resp.message`.

After the `if` block that throws, you'll place your remaining logic to process the API's response.

- [x] Await the value that `response.json()` returns. We will be working with the `records` array in the response. An example response would be:

```JSON
{
    "records": [
        {
            "id": "recEAx4TQF6JjzZLV",
            "createdTime": "2025-02-19T22:04:12.000Z",
            "fields": {
                "title": "test todo"
            }
        },
        {
            "id": "recx22h6JwjsMhCku",
            "createdTime": "2025-02-19T22:04:15.000Z",
            "fields": {
                "isCompleted": true,
                "title": "make dinner"
            }
        },
        {
            "id": "recFwX5Nyp1TpkUXI",
            "createdTime": "2025-02-19T22:04:17.000Z",
            "fields": {
                "title": "code out assignment examples"
            }
        }
    ]
}
```

There are several important details to note when you compare this response against the `todoList` state value:

- [x] The properties, `isCompleted` and `title` are stored in a `fields` object.
- [x] The `id` is at the top level of each todo object.
- [x] Any fields that equal false or contain an empty string will not be returned with the todos.
- [x] The `records` value will always be an array.

Because the "shape" of each todo is different than how they are represented in the app's `todoList` array, you will have to map the contents of `record` out of the response body. The same will be true for the payload of any PUT and PATCH requests.

- [x] in a `map` method called on `records`, define an anonymous function:
  - [x] It takes a `record` param.
  - [x] It contains a `const todo = {}`.
  - [x] Inside the object, assign the `record` properties to the appropriate todo properties.
  - [x] If `isCompleted` is not truthy, you will want to explicitly set the property equal to `false`.

Use the below `map` examples as reference if needed:

```js
//example map from an Airtable response.records

const response = await response.json();
const fetchedExamples = response.records.map((record) => {
    const example = {
        id: record.id,
        //destructuring is a compact way to move all fields over
        //won't need to change this a lot as the app evolves
        ...record.fields,
        };
    if(!example.booleanProperty){
        //Airtable doesn't return properties whose values are false or empty strings
        //explicity setting property to false so field exists and prevents logic bugs
        example.booleanProperty = false;
    }
    return example;
})
setExamples([...fetchedExamples])
```

-or a more compact version-

```js
const {records} = await response.json()
setExamples(records.map(record)=> {
    const example = {
    id: record.id,
    ...record.fields,
    };
    if(!example.booleanProperty){
        example.booleanProperty = false;
    }
    return example;
})

```

After this, it's time to move on to the `catch` and `finally` blocks.

- The `catch` block:
  - [x] Takes in an error parameter.
  - [x] Use `setErrorMessage` with `error.message` to set an error message that we will display to the user shortly.
- The `finally` bock:
  - [x] Set the `isLoading` state value back to false.

#### Display Loading Indicator in TodoList

- [x] While still in App.jsx, pass `isLoading` into props for the `TodoList` instance.
- In TodoList:
  - [x] Destructure `isLoading` out of its props.
  - [x] Add a statement that evaluates `isLoading` in the JSX that conditionally renders the existing paragraph OR a new paragraph for the loading message.
  - [x] The new paragraph should have a loading message to display the user. Eg: `<p>Todo list loading...</p>`

At this point, the todo list should display a message while the API is loading the todos. Once the fetch resolves, it re-renders with the todo list (Or the original paragraph if 0 todos are loaded).

todo list displays loading message

#### Display Error

In App:

- [x] Add conditional block after the `TodoList` instance. Use the block to evaluate `errorMessage`.
  - [x] If not empty, display a div containing:
    - [x] A horizontal rule `<hr/>`.
    - [x] A paragraph that renders `errorMessage`.
    - [x] A dismiss button that empties `errorMessage`.

When an error happens with our initial fetch, a message is displayed to the user. We've intentionally made this setup as simple as possible so that we can re-use this error message for other operation errors.

### Instructions Part 3: Update Add New Todo Functionality

In part 3, you'll use an pessimistic state update approach for adding todos. You'll use transient state to change the text content of the button while the request is processing. We don't want to pause the user but it's useful for them to know that the application is processing the last action before their todo is rendered . When the API has processed the response, the todo in the payload response gets added into the todo list state.

In App:

- [x] Create state value`isSaving` with a `defaultValue` of false. You will need its update function too.
- In the add todo button
  - [x] Replace the button text with a ternary block that evaluates `isSaving`.
    - [x] If true, display "Saving..."
    - [x] If `false`, display "Add Todo" or the text value you were already using.

It should now look like:

```jsx
<button disabled={workingTodoTitle.trim() === ''}>
    {isSaving ? 'Saving...' : 'Add Todo'}
</button>
```

- [x] Update `addTodo(newTodo)`:
  - [x] Convert it to an async function.
  - Inside the function body...
    - [x] Create a `payload` object containing a `records` array containing a single todo object.
    - [x] Create an `options` object for the fetch request:
      - [x] Use the "POST" method.
      - [x] Use the same header options from the last request.
      - [x] Stringify the `payload` object for `options.body`.

At this point, `addTodo` should look like:

```jsx
{/*extract from App.jsx*/}
{/*...code*/}

const addTodo = async (newTodo) => {
    const payload = {
      records: [
        {
          fields: {
            title: newTodo.title,
            isCompleted: newTodo.isCompleted,
          },
        },
      ],
    };
    const options = {
      method: 'POST',
      headers: {
        Authorization: token,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    };
{/*code continues...*/}
```

- Continuing from inside `addTodo`
  - `try` block logic:
    - [x] Set `isSaving` true.
    - [x] Send a fetch request and assign it's awaited return value to `resp`.
      - (hint: `const resp = await fetch(url, options);`)
      - [x] Throw an Error if `!resp.ok`
    - [x] Destructure the `records` from the response by using `const { records } = await resp.json();`
    - Create a `savedTodo` object that:
      - [x] assigns the `id` to the first array entry's id property.
      - [x] destructures the remaining key/values pairs out of the only `records` object.
    - [x] If the `isCompleted` property in the `records` object is not true, explicitly set that on property on `savedTodo` to `false`
      - [x] This looks like `if (!records[0].fields.isCompleted) {savedTodo.isCompleted = false;}`
      - [x] Recall that Airtable does not return false or empty fields in the `records`.
    - [x] Update state using `setTodoList([...todoList, savedTodo]);`
  - `catch` block logic:
    - [x] Log the error to console.
    - [x] Update `setErrorMessage` state value with `error.message`. This will cause errors to show up for users.
  - `finally` block:
    - [x] Set `isSaving` to false.

The updates you've made should flash a brief message on the button while the response processes:

saving message shows briefly on submit button

### Instructions Part 4: Update Functionality of Update and Complete Todo

For the final two refactors, you will be using an optimistic approach to UI management. This introduces the need to undo state changes and communicate unexpected API failures to the user. You'll set the updated value into state at the beginning of the `updateTodo` function but not before saving the original version temporarily. If there's a network disruption or some other issue that causes the fetch to fail, you'll use this original version to revert the todoList state back to its state before the error.

#### Update Todos Functionality

In App:

- update `updateTodo:
  - [x] Convert it to an async function.
  - [x] Save the original todo to `originalTodo`:
    - By finding it's associated object in the `todoList` array by each object's id.
    - [x] It should look like: `const originalTodo = todoList.find((todo) => todo.id === editedTodo.id)`
  - [x] Create `payload` object for the fetch request using `editedTodo`
    - [x] The API expects `payload` to be a JSON object containing a `records` array of table records for the Todo table. For reference, here's the JavaScript object you define in preparation to do this:

```JSON
const payload = {
    records: [
        {
            id: editedTodo.id,
            fields: {
                title: editedTodo.title,
                isCompleted: editedTodo.isCompleted,
            },
        },
    ],
};
```

- Continued...
  - [x] Create an `options` object for the fetch request.
    - [x] Use the PATCH method.
    - [x] Use the same Authentication header and include `'Content-Type': 'application/json'` in the `headers` object.
    - [x] For the `body` property, convert the `payload` object to a JSON string using `JSON.stringify(payload)`
  - `try` block:
    - [x] Send a fetch request using `url` as the endpoint and the `options` object just created.
      - [x] Throw an error if `!resp.ok`.
  - `catch` block:
    - [x] Log the error to console.
    - [x] Update `errorMessage` using the ``setErrorMessage(`${error.message}. Reverting todo...`);``
    - [x] Create a `revertedTodos` using the `originalTodo` to reset that todo's value to a previous state.
    - [x] Update state with `setTodoList([...revertedTodos]);`
  - `finally` block:
    - [x] Set the state value, `isSaving`, to false.

In TodoListItem:

We need to cover an edge case where an outdated value is displayed when a user saves a todo and clicks it again immediately.

- add a useEffect that resets the `workingTitle` to the `todo` prop's `.title` value
  - [x] add `todo` to the dependency array.
  - [x] call `setWorkingTitle` and pass in the value of `todo.title`

At this point, the todo app should:

1. [x] Load the todos from Airtable.
2. [x] Create new todos with the todo form and persist them in Airtable.
3. [x] Allow users to edit todos which will then update in Airtable.
4. [x] Display error messages to the user if there are any fetch issues.

error displayed to user at bottom of screen

#### Update Functionality to Complete Todos

You'll be left to update `completeTodo` with the necessary logic to communicate the completed todo to the Airtable API and keep the UI synced. You can use `updateTodo` as a reference as you work through this final portion. So that you have a checklist of details to think about: the final code should:

- Optimistically update the UI:
  - [x] The todo completes immediately in the UI immediately and allows user to continue to work with the todo list.
  - [x] The fetch request happens in the background unless there's a request error.
  - [x] The UI for the todo list reverts to its original state if the fetch response does not come back okay.
  - [x] Display an error message to the user, using the `errorMessage` state if fetch encounters any problems.
- [x] Fetch should use the same headers and method, and take in a payload very similar to the fetch found in `updateTodo`
- [x] The same object transformation has to happen between the todo object as represented in state and the todo represented in the `records` property on the payload.

### Stretch Goals: Refactor for Reusable Code

You will probably have noticed that you are starting to introduce some duplicate code. While that is okay during prototyping and early development, before submitting any final code for a feature (in our case, this assignment), take the time to refactor your code to make it **[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)**. This will keep the codebase clean and easy to manage. Remember that you should commit your code now so that you have a good save point to return to if you need to start the refactor over again.

- [x] Look for any items that are defined multiple times and assign them to a variable.
- [x] Compare functions or procedures to find common logic that could be shared in a helper or utility function.
- [x] Brainstorm some more user-friendly error messages.
- If you visual learner and have to add styling to help visualize the interface better:
  - [x] Stick to class-based styles that you define in App.css.
  - [x] Don't restructure anything in the JSX. We want to maintain a semantically sound html structure so that when we cover styling in week 10, several style choices applied during the assignment will work out properly.
  - [x] Have fun but don't let styling get away of completing the weekly lesson. After all, a baker doesn't ice a cake until after it's baked and cooled.

### Closing Notes

 Next week we cover sorting and filtering. The discussion will take us through implementing sorting and searching on both local and API data stores. We'll then implement an API-based sorting and filtering strategy.

 ### Mindset Assignment
Willingness to Experiment

For many, failure has become deeply engrained in us as something to avoid. And for that reason, as you’re learning to code, you may find that your gut response to bright red error messages or long stack traces is one of fear, anger, or frustration. But we’ll let you in on a little secret—those error messages and stack traces are a gift. (And they’re the key to learning!)
There’s no faster way to learn than to experiment often. Try your code out incrementally as you work on it and see what is or is not working the way you expect! Then put your budding debugging skills to work and figure out what’s going on. If you spend all of your time worrying about making your code perfect before running it, chances are you’ve waited too long.  If you don’t believe us, here’s a testimonial on the power of learning from failure from one of the co-founders of Stack Overflow.
Every time you encounter an error or failure is another time you have discovered what doesn’t work. That’s valuable information!
Please answer the below prompts in your assignment submission:
- Q: Think of an example of something you have done in your life that you failed at multiple times before you got it—doesn't have to be coding-related, maybe a sports play, a piece on a musical instrument, or a video game level. How did you keep yourself motivated to keep trying?
- A: I often fail while learning something new, and I have learned that failing does not have to be a setback. In fact, I embrace failure and encourage graceful failing. I have taught youth skills like skateboarding, mountain boarding, snowboarding, and mountain biking and will usually teach them how to fall before proceeding to teaching even the basics. So when I am learning a new skill, I will try and tackle it in a way that allows me to learn the steps in order to achieve the goal, and then put all of those steps together in the end.
- Q: Have you witnessed others learn from failures and then succeed? What strategies have they used?
- A: As an adventure sports instructor I get to watch my students often learn from their failures and they almost always succeed in the end. Most commonly, I've noticed that students finding a peer to work on a skill together with is a sure-fire way of seeing them both improve rapidly. Other times, they might film themself trying something and rewatching their performance will help self-guide them into improvement. Sometimes it is helpful to try and teach something you are learning in order to fully grasp the concept.

### CODE REVIEW

**Review by alenamedved — CHANGES_REQUESTED** [review]
Hello.
It looks like you've done a lot of work, but the app it growing out and already has some issues to address: 
1. it is a bug if you add a new todo and then try to complete it - it won't work, review 'addTodo' function and follow instructions from the class
`Continuing from inside addTodo
try block logic:
Set isSaving true.
Send a fetch request and assign it's awaited return value to resp.
(hint: const resp = await fetch(url, options);)
Throw an Error if !resp.ok
Destructure the records from the response by using const { records } = await resp.json();
Create a savedTodo object that:
assigns the id to the first array entry's id property.
destructures the remaining key/values pairs out of the only records object.
If the isCompleted property in the records object is not true, explicitly set that on property on savedTodo to false
This looks like if (!records[0].fields.isCompleted) {savedTodo.isCompleted = false;}
Recall that Airtable does not return false or empty fields in the records.
Update state using setTodoList([...todoList, savedTodo]);
catch block logic:
Log the error to console.
Update setErrorMessage state value with error.message. This will cause errors to show up for users.
finally block:
Set isSaving to false.`
2. another issue I've noticed related to css: when it is an error, the todo's block changes the width, it is not a good practice when in ui something like this happens it doesn't look good

My advice, keep it simple and follow instructions, I hope you understand everything you submit

File: src/App.jsx [hunk 1]
```diff
@@ -80,14 +80,30 @@ function App() {
...
       },
     ];
     setTodoList(optimisticTodos);
     try {
-      await createRequest('POST', payload);
+      const { records } = await createRequest('POST', payload);
+      const firstRecord = records?.[0];
+      const fields = firstRecord?.fields ?? {};
+
+      if (!firstRecord?.id) throw new Error('No record returned from API');
```
Comment (alenamedved) [inline src/App.jsx]: nit:The successful Airtable response will always have an id. While if (!firstRecord?.id) is safe 'defensive' code, it’s technically redundant if your createRequest helper already throws on non-200 status codes.

Comment (mnichols08) [reply src/App.jsx]: I will remove this line
